import "server-only";

import type {
  CampaignProjection,
  CampaignReadinessEvidence,
  CandidateWorkspaceReadEvidence,
  EffectiveMembership,
  GuidedIntakeReadEvidence,
  TenantMeResponse,
} from "@/lib/contracts";

export const DEMO_TENANT_ID = "11111111-1111-4111-8111-111111111111";
export const DEMO_CAMPAIGN_ID = "22222222-2222-4222-8222-222222222222";

export const demoMemberships: readonly EffectiveMembership[] = [
  {
    membership_id: "33333333-3333-4333-8333-333333333333",
    campaign_id: null,
    roles: ["portfolio_operator"],
    grants: [
      {
        grant_id: "44444444-4444-4444-8444-444444444444",
        campaign_id: null,
        workspace_id: null,
        action: "create",
        resource_type: "campaign_collection",
        resource_id: DEMO_TENANT_ID,
        purpose: "Create tenant campaign",
        approval_receipt_id: "synthetic-demo-approval",
      },
      {
        grant_id: "55555555-5555-4555-8555-555555555555",
        campaign_id: DEMO_CAMPAIGN_ID,
        workspace_id: null,
        action: "read",
        resource_type: "campaign",
        resource_id: DEMO_CAMPAIGN_ID,
        purpose: "Operate assigned campaign",
        approval_receipt_id: "synthetic-demo-approval",
      },
      {
        grant_id: "66666666-6666-4666-8666-666666666666",
        campaign_id: DEMO_CAMPAIGN_ID,
        workspace_id: null,
        action: "read",
        resource_type: "campaign_readiness",
        resource_id: DEMO_CAMPAIGN_ID,
        purpose: "Assess assigned campaign readiness",
        approval_receipt_id: "synthetic-demo-approval",
      },
      {
        grant_id: "99999999-9999-4999-8999-999999999999",
        campaign_id: DEMO_CAMPAIGN_ID,
        workspace_id: null,
        action: "read",
        resource_type: "guided_intake",
        resource_id: DEMO_CAMPAIGN_ID,
        purpose: "Review guided campaign intake",
        approval_receipt_id: "synthetic-demo-approval",
      },
      {
        grant_id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
        campaign_id: DEMO_CAMPAIGN_ID,
        workspace_id: null,
        action: "read",
        resource_type: "candidate_workspace",
        resource_id: DEMO_CAMPAIGN_ID,
        purpose: "Review candidate evidence workspace",
        approval_receipt_id: "synthetic-demo-approval",
      },
    ],
  },
];

export const demoTenantIdentity: TenantMeResponse = {
  principal_id: "77777777-7777-4777-8777-777777777777",
  tenant_id: DEMO_TENANT_ID,
  subject: "synthetic-demo-operator",
  issuer: "https://demo.invalid/",
  display_name: "Operadora Demo",
  email: null,
  authenticated_at: "2026-07-21T00:00:00Z",
  evaluated_at: "2026-07-21T00:00:00Z",
  application_memberships: demoMemberships,
  authorization_status: "LOADED",
};

export const demoCampaign: CampaignProjection = {
  id: DEMO_CAMPAIGN_ID,
  tenant_id: DEMO_TENANT_ID,
  slug: "antigua-demo",
  name: "Campaña sintética Antigua",
  jurisdiction: "Antigua Guatemala",
  stage: "PRECAMPAIGN",
  status: "DRAFT",
  version: 1,
};

export const demoReadiness: CampaignReadinessEvidence = {
  audit_event_id: "88888888-8888-4888-8888-888888888888",
  readiness: {
    tenant_id: DEMO_TENANT_ID,
    campaign_id: DEMO_CAMPAIGN_ID,
    campaign_version: 1,
    campaign_status: "DRAFT",
    readiness_scope: "OPERATIONAL_SETUP_ONLY",
    status: "READY_FOR_GUIDED_INTAKE",
    ready_for_guided_intake: true,
    completed_checks: 4,
    total_checks: 4,
    active_workspace_count: 1,
    next_action: "BEGIN_GUIDED_INTAKE",
    checks: [
      { key: "campaign_name", complete: true, reason_code: "CAMPAIGN_NAME_PRESENT" },
      { key: "jurisdiction", complete: true, reason_code: "JURISDICTION_PRESENT" },
      { key: "campaign_stage", complete: true, reason_code: "CAMPAIGN_STAGE_PRESENT" },
      { key: "active_workspace", complete: true, reason_code: "ACTIVE_WORKSPACE_PRESENT" },
    ],
    limitation_codes: [
      "NOT_A_HUMAN_APPROVAL",
      "NO_STRATEGY_EVIDENCE_OR_CITIZEN_ASSESSMENT",
    ],
  },
};

export const demoGuidedIntake: GuidedIntakeReadEvidence = {
  audit_event_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
  intake: {
    id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    tenant_id: DEMO_TENANT_ID,
    campaign_id: DEMO_CAMPAIGN_ID,
    campaign_version: 1,
    campaign_status: "DRAFT",
    campaign_name: demoCampaign.name,
    jurisdiction: demoCampaign.jurisdiction,
    stage: demoCampaign.stage,
    active_workspace_count: 1,
    readiness_scope: "GUIDED_INTAKE_ONLY",
    status: "READY_FOR_RESEARCH",
    ready_for_research: true,
    office: "Alcaldía Municipal",
    candidate_project: "Proyecto ciudadano sujeto a validación documental y autoridad humana.",
    current_team: ["Dirección de campaña", "Investigación"],
    current_assets: [],
    budget_status: "ROUGH_RANGE",
    known_unknowns: ["Requisitos jurídicos", "Capacidad territorial"],
    evidence_requirements: ["Biografía verificable", "Marco electoral aplicable"],
    completed_checks: 8,
    total_checks: 8,
    next_action: "BEGIN_RESEARCH",
    checks: [
      {
        key: "campaign_operational_setup",
        complete: true,
        reason_code: "CAMPAIGN_OPERATIONAL_SETUP_COMPLETE",
      },
      { key: "office", complete: true, reason_code: "TARGET_OFFICE_DEFINED" },
      {
        key: "candidate_project",
        complete: true,
        reason_code: "CANDIDATE_PROJECT_DESCRIBED",
      },
      { key: "current_team", complete: true, reason_code: "CURRENT_TEAM_ASSESSED" },
      { key: "current_assets", complete: true, reason_code: "CURRENT_ASSETS_ASSESSED" },
      { key: "budget_status", complete: true, reason_code: "BUDGET_EVIDENCE_ASSESSED" },
      {
        key: "known_unknowns",
        complete: true,
        reason_code: "KNOWN_UNKNOWNS_RECORDED",
      },
      {
        key: "evidence_requirements",
        complete: true,
        reason_code: "EVIDENCE_REQUIREMENTS_DEFINED",
      },
    ],
    research_first_actions: [
      "VERIFY_OFFICE_AND_JURISDICTION_EVIDENCE",
      "VALIDATE_CANDIDATE_PROJECT_EVIDENCE",
      "ASSESS_TEAM_CAPACITY_GAPS",
      "INVENTORY_ASSET_PROVENANCE",
      "DOCUMENT_BUDGET_ASSUMPTIONS",
      "RESEARCH_KNOWN_UNKNOWNS",
      "COLLECT_REQUIRED_EVIDENCE",
    ],
    limitation_codes: [
      "NOT_A_STRATEGY",
      "NOT_A_HUMAN_APPROVAL",
      "NO_CITIZEN_CONTACT_OR_PROFILING",
      "NO_EXTERNAL_EFFECTS",
    ],
    version: 1,
    created_at: "2026-07-21T00:00:00Z",
    updated_at: "2026-07-21T00:00:00Z",
  },
};

export const demoCandidateWorkspace: CandidateWorkspaceReadEvidence = {
  audit_event_id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  workspace: {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
    tenant_id: DEMO_TENANT_ID,
    campaign_id: DEMO_CAMPAIGN_ID,
    campaign_version: 1,
    campaign_status: "DRAFT",
    campaign_name: demoCampaign.name,
    jurisdiction: demoCampaign.jurisdiction,
    candidate_id: "ffffffff-ffff-4fff-8fff-ffffffffffff",
    display_name: "Candidatura sintética",
    status: "SETUP_REQUIRED",
    public_use_status: "BLOCKED",
    external_effects: "NONE",
    evidence: [],
    identity: null,
    biography: null,
    purpose: null,
    values: null,
    attributes: null,
    contradictions: null,
    development_goals: null,
    reputation_risks: null,
    checks: [
      { key: "identity", complete: false, reason_code: "IDENTITY_NOT_VERIFIED" },
      { key: "biography", complete: false, reason_code: "BIOGRAPHY_NOT_VERIFIED" },
      { key: "purpose", complete: false, reason_code: "PURPOSE_NOT_VERIFIED" },
      { key: "values", complete: false, reason_code: "VALUES_NOT_VERIFIED" },
      { key: "attributes", complete: false, reason_code: "ATTRIBUTES_NOT_VERIFIED" },
      { key: "contradictions", complete: false, reason_code: "CONTRADICTIONS_UNRESOLVED" },
      { key: "development_goals", complete: false, reason_code: "DEVELOPMENT_GOALS_MISSING" },
      { key: "reputation", complete: false, reason_code: "REPUTATION_RISKS_UNRESOLVED" },
      { key: "approvals", complete: false, reason_code: "CURRENT_SECTION_APPROVALS_REQUIRED" },
    ],
    completed_checks: 0,
    total_checks: 9,
    approvable_sections: [],
    current_approved_sections: [],
    approvals_required: [],
    open_critical_high_risks: 0,
    next_action: "DEFINE_IDENTITY",
    limitation_codes: [
      "NOT_PUBLIC_POSITIONING_APPROVAL",
      "NOT_A_STRATEGY",
      "NO_VOTER_PROFILING",
      "NO_EXTERNAL_EFFECTS",
      "HUMAN_REVIEW_REQUIRED",
    ],
    version: 1,
    created_at: "2026-07-21T00:00:00Z",
    updated_at: "2026-07-21T00:00:00Z",
  },
};
